from pathlib import Path

# ROOT DIRECTORY
ROOT_DIR = Path(__file__).resolve().parents[2]


# DATA DIRECTORIES
DATA_DIR = ROOT_DIR / "data"

RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"


# ARTIFACT DIRECTORIES
ARTIFACTS_DIR = ROOT_DIR / "artifacts"

MODELS_DIR = ARTIFACTS_DIR / "models"
METRICS_DIR = ARTIFACTS_DIR / "metrics"
PREDICTIONS_DIR = ARTIFACTS_DIR / "predictions"
REPORTS_DIR = ARTIFACTS_DIR / "reports"
PRODUCTION_MODEL_DIR = MODELS_DIR / "production"

# CONFIG DIRECTORIES
CONFIG_DIR = ROOT_DIR / "configs"


# TEST DIRECTORIES
TESTS_DIR = ROOT_DIR / "tests"
FIXTURES_DIR = TESTS_DIR / "fixtures"